Logging Improvements
guardian/multimedia-watchman pull request #9
Opened 2019-01-29 15:26 UTC by Dala0

Changes the default log level to INFO.

Adds support for loading the global log level from the <log-level> tag if present. Legal values are CRITICAL, ERROR, WARNING, INFO, and DEBUG. This value is then used to change the log level setting of the main logger object.

Adds support for loading path specific log levels from the <log-level> tag if present for that path. Legal values are CRITICAL, ERROR, WARNING, INFO, and DEBUG. This value is then used to change the log level of unique child logger objects called from the WatchDogBasedSystem and WatchmanBlacklist classes.

Tested on a local virtual machine.

@fredex42

2019-01-29 15:41 UTC, Dala0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make Watchman Read Log Level Settings from the Config. File](https://trello.com/c/3kCMvwLl/3004-make-watchman-read-log-level-settings-from-the-config-file)

2019-02-04 10:39 UTC, fredex42 commented on watcher/blacklist.py
> +            pass
would be nice to output a WARNING here if something fails, just so we know

2019-02-04 10:40 UTC, fredex42 requested changes
one tiny change, see inline

2019-02-04 13:28 UTC, Dala0 commented on watcher/blacklist.py
> +            pass
Done.

2020-01-09 14:51 UTC, fredex42 approved these changes
👍

2020-01-09 15:08 UTC, merged